modLoader = "javafml"
loaderVersion = "[2,)"
license = "MIT"

[[mods]]
modId = "newzealandnatives"
version = "${version}"
displayName = "New Zealand Natives"
authors = "BlazeBSC"
description = "Minecraft Mod that adds various NZ native animals, trees and plants to the game."

[[dependencies.newzealandnatives]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.newzealandnatives]]
modId = "geckolib"
type = "required"
versionRange = "[4.9,)"
ordering = "NONE"
side = "BOTH"
