pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        gradlePluginPortal()
    }
}

plugins {
    id("dev.kikugie.stonecutter").version "0.9.8"
}

stonecutter {
    // Enable Groovy DSL, as Stonecutter uses Kotlin by default
    kotlinController = false
    centralScript = "build.gradle"

    create(rootProject) {
        versions '1.21.1', '1.21.11'
    }
}
